importing the dependencies

In [ ]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [ ]:
#loading dataset to a pandas dataframe
credit_card_data = pd.read_csv('/content/creditcard.csv')

In [ ]:
credit_card_data.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0.0
1,0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0.0
2,1,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0.0
3,1,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0.0
4,2,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0.0

In [ ]:
credit_card_data.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
40768,40392,0.180367,-2.320091,-2.393357,-0.099322,1.438798,3.376369,0.420557,0.468550,-1.594167,...,-0.019143,-1.169199,-0.669946,0.998749,0.653483,-0.332582,-0.104583,0.122331,653.56,0.0
40769,40393,-0.347533,0.462031,0.413834,-1.403547,0.251277,-0.201277,0.706570,-0.173221,-1.638856,...,-0.217763,-0.738272,0.144049,-0.878037,-0.615576,-0.686502,0.064940,0.161659,80.65,0.0
40770,40393,1.071611,0.067492,0.283197,1.243709,0.024615,0.109673,0.129178,-0.026332,0.126973,...,-0.165087,-0.433136,-0.080091,-0.423704,0.522372,-0.446441,0.036590,0.030713,73.10,0.0
40771,40393,-2.687835,1.069146,1.543733,-1.521685,-0.041831,0.331681,1.302125,-0.826599,0.741611,...,-1.271315,-1.318991,-0.126223,-0.400434,0.312811,0.023125,0.320880,0.045527,75.00,0.0
40772,40393,1.087233,-0.919047,0.097149,0.185226,-0.404768,0.986686,-0.612788,0.126250,-0.750372,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
#dataset information
credit_card_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40773 entries, 0 to 40772
Data columns (total 31 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Time    40773 non-null  int64
 1   V1      40773 non-null  float64
 2   V2      40773 non-null  float64
 3   V3      40773 non-null  float64
 4   V4      40773 non-null  float64
 5   V5      40773 non-null  float64
 6   V6      40773 non-null  float64
 7   V7      40773 non-null  float64
 8   V8      40773 non-null  float64
 9   V9      40773 non-null  float64
 10  V10     40773 non-null  float64
 11  V11     40773 non-null  float64
 12  V12     40773 non-null  float64
 13  V13     40772 non-null  float64
 14  V14     40772 non-null  float64
 15  V15     40772 non-null  float64
 16  V16     40772 non-null  float64
 17  V17     40772 non-null  float64
 18  V18     40772 non-null  float64
 19  V19     40772 non-null  float64
 20  V20     40772 non-null  float64
 21  V21     40772 non-null  float64
 22  V22     40772 non-null  float64
 23  V23     40772 non-null  float64
 24  V24     40772 non-null  float64
 25  V25     40772 non-null  float64
 26  V26     40772 non-null  float64
 27  V27     40772 non-null  float64
 28  V28     40772 non-null  float64
 29  Amount  40772 non-null  float64
 30  Class   40772 non-null  float64
dtypes: float64(30), int64(1)
memory usage: 9.6 MB

In [ ]:
#checking the number of missing values in each column
credit_card_data.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       1
V14       1
V15       1
V16       1
V17       1
V18       1
V19       1
V20       1
V21       1
V22       1
V23       1
V24       1
V25       1
V26       1
V27       1
V28       1
Amount    1
Class     1
dtype: int64

In [ ]:
#handling missing values
columns_with_missing = credit_card_data.columns[credit_card_data.isnull().any()]

In [ ]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(strategy='median')
credit_card_data[columns_with_missing] = imputer.fit_transform(credit_card_data[columns_with_missing])

In [ ]:
#distribution of legit transactions & fraudulent transactions
credit_card_data['Class'].value_counts()

0.0    40667
1.0      106
Name: Class, dtype: int64

This dataset is highly unbalanced
0 --> normal
1 --> fraudulent

In [ ]:
#separating the data for analysis
legit = credit_card_data[credit_card_data.Class == 0]
fraud = credit_card_data[credit_card_data.Class == 1]

In [ ]:
print(legit.shape)
print(fraud.shape)

(40667, 31)
(106, 31)

In [ ]:
# statistical measures of the data
legit.Amount.describe()

count    40667.000000
mean        88.594198
std        237.052361
min          0.000000
25%          7.500000
50%         23.940000
75%         79.945000
max       7879.420000
Name: Amount, dtype: float64

In [ ]:
fraud.Amount.describe()

count     106.000000
mean       95.258113
std       252.913023
min         0.000000
25%         1.000000
50%         3.440000
75%        99.990000
max      1809.680000
Name: Amount, dtype: float64

In [ ]:
# compare the values for both transactions
credit_card_data.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0.0,25899.929574,-0.199868,0.026016,0.742102,0.173189,-0.219551,0.106476,-0.093367,0.033831,0.211280,...,0.046327,-0.030535,-0.111319,-0.039719,0.008348,0.135501,0.023133,0.005960,0.004832,88.594198
1.0,21051.084906,-7.530916,5.695863,-10.699793,5.819103,-5.287100,-2.259022,-7.479055,3.752600,-2.893803,...,0.649565,0.610360,-0.349569,-0.342602,-0.233497,0.311947,0.175150,0.797127,0.100630,95.258113

##under-sampling

build a sample dataset containing similar distribution of normal transactions and fraudulent transactions

In [ ]:
legit_sample = legit.sample(n=106)

concatenating two data frames

In [ ]:
new_dataset = pd.concat([legit_sample, fraud], axis = 0)

In [ ]:
new_dataset.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
6426,7610,-0.420729,0.876246,1.846851,1.240651,0.328010,-0.167012,0.534237,-0.227104,1.055830,...,-0.226312,-0.202165,-0.070257,-0.240071,-0.256847,-0.413367,0.207013,-0.016190,36.00,0.0
40629,40325,1.132656,0.029896,0.393554,1.293173,-0.268812,0.087189,-0.180694,0.247901,0.341241,...,-0.077457,-0.106919,-0.045162,-0.030216,0.566315,-0.322006,0.024020,0.000219,2.00,0.0
14145,25153,1.012486,-0.102863,2.381436,3.220555,-1.115558,1.491994,-1.408520,0.505790,2.421239,...,-0.061211,0.604555,-0.070663,0.084483,0.381118,0.241144,0.085478,0.029580,0.04,0.0
25859,33799,-0.857869,0.488899,1.292385,0.719527,-0.595626,0.839315,-0.132652,0.958006,0.355617,...,0.119280,0.301065,0.034283,-0.376397,-0.304220,-0.373728,0.051859,0.086530,69.53,0.0
1842,1430,1.480046,-1.226467,0.677911,-1.495728,-1.743645,-0.328698,-1.453529,0.101518,-1.631921,...,-0.046509,0.185021,-0.037522,-0.046650,0.310160,-0.095382,0.039255,0.010660,11.20,0.0

In [ ]:
new_dataset.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
31002,36170,-5.685013,5.776516,-7.064977,5.902715,-4.715564,-1.755633,-6.958679,3.877795,-5.541529,...,1.128641,-0.962960,-0.110045,-0.177733,-0.089175,-0.049447,0.303445,0.219380,111.70,1.0
33276,37167,-7.923891,-5.198360,-3.000024,4.420666,2.272194,-3.394483,-5.283435,0.131619,0.658176,...,-0.734308,-0.599926,-4.908301,0.410170,-1.167660,0.520508,1.937421,-1.552593,12.31,1.0
39183,39729,-0.964567,-1.643541,-0.187727,1.158253,-2.458336,0.852222,2.785163,-0.303609,0.940006,...,0.447180,0.536204,1.634061,0.203839,0.218749,-0.221886,-0.308555,-0.164500,776.83,1.0
40085,40086,1.083693,1.179501,-1.346150,1.998824,0.818034,-0.771419,0.230307,0.093683,-0.167594,...,-0.312000,-0.639700,-0.120249,-0.180218,0.609283,-0.339524,0.096701,0.114972,1.00,1.0
40525,40276,1.159373,2.844795,-4.050680,4.777701,2.948980,-2.010361,1.744086,-0.410287,-2.450198,...,-0.176541,-0.433470,-0.529323,-0.597020,1.335954,0.547092,0.009979,0.160769,1.00,1.0

In [ ]:
new_dataset['Class'].value_counts()

0.0    106
1.0    106
Name: Class, dtype: int64

In [ ]:
# splitting data into features and targets
X = new_dataset.drop(columns = 'Class', axis = 1) #--> features
Y = new_dataset['Class'] #--> targets

In [ ]:
# split the data into training data and testing data
X_train, X_test, Y_train, Y_test = train_test_split(X,Y, test_size = 0.2, stratify = Y, random_state = 2)

In [ ]:
#Model Training
model = LogisticRegression(max_iter=1000)
model.fit(X_train, Y_train)

LogisticRegression(max_iter=1000)

In [ ]:
#Model Evaluation
#Accuracy on training data
X_train_pred = model.predict(X_train)
training_data_accuracy = accuracy_score(X_train_pred, Y_train)

In [ ]:
print("Accuracy on training data: ", training_data_accuracy)

Accuracy on training data:  0.9585798816568047

In [ ]:
#accuracy on test data
X_test_pred = model.predict(X_test)
test_data_accuracy = accuracy_score(X_test_pred, Y_test)

In [ ]:
print("Accuracy on training data: ", test_data_accuracy)

Accuracy on training data:  0.9069767441860465